version: "3.9"
services:

  grafana:
    image: grafana/grafana:8.5.3-ubuntu
    ports:
    - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
      - ./prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
  prometheus:
    image: prom/prometheus:v2.36.0
    ports:
    - "9090:9090"
    volumes:
    - prom-data:/prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  grafana-data:
  grafana-configs:
  prom-data:

